### ISSUE TITLE
while migrating database using command prompt , ModuleNotFound Error comes for django-suit

### ISSUE THREAD

**Issue by sarthak1122** [Cloud-CV/CloudCV#146]
while i was setting up the enviornment for cloudCV development , after running the command "python manage.py migrate --settings=settings.dev.settings" peek in and when i searched it on stack over flow it said i should try chainging the version of django-suit in the requirements.txt file but it didnt helped ! 

Here is the error :

Traceback (most recent call last):
  File "D:\cloudCV\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\SARTHAK\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\SARTHAK\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\SARTHAK\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\SARTHAK\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\SARTHAK\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\SARTHAK\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'suit'

@Ram81 can u pls look into the issue ? Thnks

**Comment by satyajeetch1991** [comment]
### Solution for ModuleNotFoundError: 'suit'

1. **Replace django-suit with maintained fork**:
```bash
pip uninstall django-suit
pip install django-suit2
